### ISSUE TITLE
Safari extracts file automatically and keeps only the first file with zeroHeaders and streamed files

### ISSUE THREAD

**Issue by digilist** [maennchen/ZipStream-PHP#164] opened 2020-10-29 13:52 UTC
# Description of the problem

Safari on MacOS extracts downloaded Zip files automatically. I noticed that when using zeroHeaders only the first file is kept, all other files in the zip archive are discarded.

I do not know if this is a problem with Safari or with the generated Zip file. But I need to use zero headers as I am adding files from remote streams which do not support seeking.

For the example below there is only a file test1.jpg in the download folders. If I disable zeroHeaders, the test.zip file is in the download folder.

# Example code

```php
$options = new Archive();
$options->setSendHttpHeaders(true);
$options->setZeroHeader(true);

$zipStream = new ZipStream('test.zip', $options);
$zipStream->addFileFromStream('test1.jpg', fopen('test1.jpg', 'r'));
$zipStream->addFileFromStream('test2.jpg', fopen('test2.jpg', 'r'));

$zipStream->finish();
```

# Information

* ZipStream-PHP version: 1.2.0 and 2.1.0
* PHP version: 7.4

**Comment by NicolasCARPi** [comment] 2020-10-29 14:01
I'm not sure if we can do something about it, it seems to be a Safari specific bug. So you might want to disable auto open files after download in Safari config.

**Comment by maennchen** [comment] 2020-10-29 16:03
@digilist You could also try if it makes a difference if you put the files into a directory.

```php
$zipStream->addFileFromStream('dir/test1.jpg', fopen('test1.jpg', 'r'));
$zipStream->addFileFromStream('dir/test2.jpg', fopen('test2.jpg', 'r'));
```

**Comment by digilist** [comment] 2020-10-29 20:53
Thank you for your quick reply. Putting all files into a folder sounded like a great workaround, so I tried it out. Unfortunately it has the same effect. The only difference this time is that the first file is put into the folder, but the other files are still not there :(

**Comment by maennchen** [comment] 2020-10-29 23:11
@digilist Sorry, then I have no idea as well...

**Comment by digilist** [comment] 2020-10-30 10:12
No problem, thank you nevertheless :)

**Comment by maennchen** [comment] 2020-11-04 00:06
I added a `wontfix` label since the core maintainers do not have access to OSX machines and do not have the time to track down this specific bug.

If anyone can come up with a solution (& maybe even a test for the CI), that is still greatly appreciated and a PR would be very welcome.

**Closed by maennchen** 2020-11-04 00:06 UTC
Labels: bug, wontfix

**Comment by pieterdt** [comment] 2021-03-03 13:04
Hi, I have OSX and a customer of mine is suffering the same problem.
The problem is not related to Safari I think. It is even a pretty weird problem.
I have 2 osx laptops running the latest release. On one, the zip file extracts without issues, on the other, only the first file lands extracted.

So, I'm certainly interested in helping out, the problem however, is that I have no clue as to what could possibly cause this difference in behaviour, and even then, how to get an understanding what goes wrong in those unzip tools as they are closed software. 

Also worth noting: on the machines that have said issue, unzipping with other tools works just fine (terminal unzip command or keka.app)

**Comment by NicolasCARPi** [comment] 2021-03-03 13:38
@pieterdt I think at this point the best course of action is to recommand users to extract the archive using a tool that actually works, and not to rely on broken mac software.

**Comment by macku99** [comment] 2021-03-04 03:48
I have exactly the same problem, and setting enableZip64 to false, seems to resolve the issue. I am not sure if this is the real solution; however, I can consistently replicate the problem and the desired behaviour when I turn the setting on and off. I hope it helps.

**Comment by pieterdt** [comment] 2021-03-04 08:25
unfortunately I need to support zips that could be larger than 4GB. I've had several users with complaints before I went from 0.5.2 to 2.01, but I have the feeling that the problem in this form was not reported. I'm currently doing a lot of tests to confirm if 0.5.2 worked better in that respect. Will update here.

**Comment by grantholle** [comment] 2024-06-05 20:30
@macku99 It looks like you are on the right track, as was discovered by a similar [Python](https://github.com/uktrade/stream-zip/pull/42) library. Thanks for the lead.

Seems insane that this is the case with Safari.
