### ISSUE TITLE
Add files in subfolder

### ISSUE THREAD

**Issue by bastien70** [maennchen/ZipStream-PHP#203] opened 2022-01-06 15:33 UTC
# Description of the problem

How can I create folder and add files in ?

# Informations

* ZipStream-PHP version: 2.1.0
* PHP version: 8.0

I followed the #78 

`$zip->addFile('directory/', '');` but it doesn't create folder. Is there a method to do it ?

**Comment by maennchen** [comment] 2022-01-06 16:46
Duplicate of #78

**Closed by maennchen** 2022-01-06 16:46 UTC

**Comment by ahmed-bhs** [comment] 2023-02-07 14:52
@bastien70 did you found any solution to create an empty folder ?
