### ISSUE TITLE
Zip file from a remote URL

### ISSUE THREAD

**Issue by vipera7** [maennchen/ZipStream-PHP#60] opened 2017-10-11 10:18 UTC
Hello !

I would like to put file from an URL to a zip archive and to be able to download it from the browser.
I heard of the function `addFileFromStream` but I don't know how to use it properly.

here it is the code I made by now but not working:

```php
require 'vendor/autoload.php';

// create a new zipstream object
$zip = new ZipStream\ZipStream('example.zip');

// create a file named 'hello.txt' 
$zip->addFile('hello.txt', 'This is the contents of hello.txt');

// add a file named 'README.md' from a local file 'README.md'
$zip->addFileFromPath('README.md', 'README.md');

//My remote file
$file ="https://host/file.txt";

$fp = tmpfile();
$ch = curl_init($file);
curl_setopt($ch, CURLOPT_TIMEOUT, 120);
curl_setopt($ch, CURLOPT_FILE, $fp);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_exec($ch);
curl_close($ch);
//rewind($fp);
$stream = readfile($file);
rewind($fp);
$zip->addFileFromStream("file.txt", $stream);
fclose($fp);
// finish the zip stream
$zip->finish();
```

**Comment by vipera7** [comment] 2017-10-11 11:36
I found the solution
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use ZipStream\ZipStream;

// Create new Zip
$zip = new ZipStream("hi.zip");

// add a lot of http urls
$urls = [
  'http://img31.mtime.cn/pi/2014/10/22/092931.12614666_1000X1000.jpg',
  'http://img31.mtime.cn/pi/2014/10/22/092931.79193700_1000X1000.jpg',
];

foreach($urls as $url) {
  // Create Temp File
  $fp = tmpfile();

  // Download File
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_FILE, $fp);
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_exec($ch);

  // Force to write all data
  fflush($fp);

  // Rewind to the beginning, otherwise the stream is at the end from the start
  rewind($fp);

  // Find out a file name from url
  // In this case URL http://img31.mtime.cn/pi/2014/10/22/092931.12614666_1000X1000.jpg will yield
  // /pi/2014/10/22/092931.12614666_1000X1000.jpg as file path
  $filename = parse_url($url, PHP_URL_PATH);

  // Add File
  $zip->addFileFromStream($filename, $fp);

  // Close the Temp File
  fclose($fp);
}

// Finish ZIP
$zip->finish();

```

But now the problem is if the file have a size of 4GB I'm not able to get it.

**Comment by maennchen** [comment] 2017-10-11 12:55
Hi @vipera7 

That's because of missing Large File Support (Zip64) #30 
I unfortunately currently do not have the time to add support.

**Comment by maennchen** [comment] 2017-10-11 12:55
(Closing because of duplicate of #30)

**Closed by maennchen** 2017-10-11 12:55 UTC
