### ISSUE TITLE
.zip to .zip.cpgz infinite loop on mac

### ISSUE THREAD

**Issue by ArturGrigio** [maennchen/ZipStream-PHP#27] opened 2015-01-28 01:21 UTC
On a mac, the downloaded zip enters into a .zip to .zip.cpgz infinite loop (apparently OSX creates the .cpgz to read what's inside the .zip, but it fails and it creates a .zip and so on...).

I believe it's got something to do with the headers.

Can someone please look into this?

**Comment by donatj** [comment] 2015-01-28 01:50
What version are you using?

**Comment by donatj** [comment] 2015-01-28 01:53
Also if you could create a small sample that causes the issue, that'd be very helpful

**Comment by ArturGrigio** [comment] 2015-01-31 00:36
1) I've downloaded the latest version from git
2) I installed it on PHP Version 5.3.29
3) I tested it on OSX Mavericks and Yosemite (virtual machine)
4) I am not using any third party software (i.e. winrar)

I wrote my own version of something similar (https://github.com/ArturGrigio/php-Zip-Download-of-Large-Files-using-Buffer), and I was having the same loop issue. The fix for mine was static casing the stream command to string before sending to the buffer. I believe something about the escape characters was messing with it.

**Comment by maennchen** [comment] 2015-01-31 08:02
Is it possible to send us the file and the exact code you're running?

**Comment by donatj** [comment] 2015-02-01 03:05
Yes, if you could send us the code and/or an example zip that would be very helpful resolving this.

**Comment by maennchen** [comment] 2015-02-18 08:41
We can't reproduce the error if we don't have this data. I'm therefore closing the issue.
Feel free to reopen it, if we have the required data.

**Closed by maennchen** 2015-02-18 08:41 UTC

**Comment by pooshok** [comment] 2016-01-26 12:31
Here is the solution https://github.com/splitbrain/crocofile/issues/2

**Comment by maennchen** [comment] 2016-01-26 12:42
@pooshok The change referenced in you link was implemented years ago...
https://github.com/maennchen/ZipStream-PHP/blob/master/src/ZipStream.php#L413

**Comment by pooshok** [comment] 2016-01-26 13:04
Oh! sorry. I downloaded and used version 0.2.2 from here http://pablotron.org/software/zipstream-php/ and thought it latest.

**Comment by maennchen** [comment] 2016-01-26 13:25
@pooshok:
There aren't any changes on the original since the year 2004. That's why I forked it.

**Comment by code8082** [comment] 2017-10-04 18:46
I'm having this same error when I try to zip files dynamically.

`<?php
ob_start();
# load zipstream class
require 'zipstream/ZipStream.php';

$zip = new ZipStream\ZipStream('download.zip');

// connect to the database
include('connect-db.php');

$project_id_temp = '75';

$query = "SELECT * FROM `project_images` WHERE project_id = ".$project_id_temp;
$result = $conn->query($query);

if ($result == false) {
$error_message = $conn->error;
echo "<p>An error occurred: $error_message</p>";
exit () ;
}

$row_count = $result->num_rows;



if(mysqli_num_rows($result) > 0){
    for ($i = 0; $i < $row_count; $i++) :
   		$image = $result->fetch_assoc();
		$zip->addFileFromPath($image['img_name'], "uploads/".$project_id_temp."/".$image['img_name']);
	endfor; 
$zip->finish();
} 
?>`

**Comment by code8082** [comment] 2017-10-04 18:49
I'm having the same problem when I try to zip files dynamically. It just keeps making these zips that open into cpgz in an infinite loop. 

`<?php
ob_start();
// load zipstream class
require 'zipstream/ZipStream.php';

$zip = new ZipStream\ZipStream('download.zip');

// connect to the database
include('connect-db.php');

$project_id_temp = '75';

$query = "SELECT * FROM `project_images` WHERE project_id = ".$project_id_temp;
$result = $conn->query($query);

if ($result == false) {
$error_message = $conn->error;
echo "<p>An error occurred: $error_message</p>";
exit () ;
}

$row_count = $result->num_rows;



if(mysqli_num_rows($result) > 0){
    for ($i = 0; $i < $row_count; $i++) :
   		$image = $result->fetch_assoc();
		$zip->addFileFromPath($image['img_name'], "uploads/".$project_id_temp."/".$image['img_name']);
	endfor; 
$zip->finish();
} 
?>`

**Comment by maennchen** [comment] 2017-10-04 20:18
@code8082 Can you look at the zip file with a text editor and make sure that there are no PHP warnings?

**Comment by code8082** [comment] 2017-10-04 20:58
No warnings I can see. If i hard code the files it works fine. If i dynamically add them like above, it doesn't work and makes this zip that creates a cpgz file and then a zip and then a cpgz file.

Hard-coded version:
`<?php
require 'zipstream/ZipStream.php';

$zip = new ZipStream\ZipStream('download.zip');

$zip->addFileFromPath("7736c57f9fdc596cc8f919f362e92878_3cd0ba0d24d7b.jpg", "uploads/75/7736c57f9fdc596cc8f919f362e92878_3cd0ba0d24d7b.jpg");

$zip->addFileFromPath("b460e068faf57f6ed84f84114ea2368f_862f49e57c899.jpg", "uploads/75/b460e068faf57f6ed84f84114ea2368f_862f49e57c899.jpg");

$zip->finish();

?>`

**Comment by maennchen** [comment] 2017-10-04 21:43
@code8082 If it works hard-coded it‘s likely not an error of the library. Could you try to dump the files instead of adding them to a zip to see if you code other than the zip works?

**Comment by donatj** [comment] 2017-10-04 21:45
@code8082 Could you try removing the closing php tag `?>` sometimes accidental trailing whitespace can cause nightmares.

**Comment by code8082** [comment] 2017-10-04 22:40
Hey donatj... I tried removing the `?>` tag.. same issue. 

how do i dump the files maennchen?

**Comment by SOSTheBlack** [comment] 2018-03-07 20:08
This worked for me and fixed my bug.

```php
ob_end_clean();
readfile('name.zip');
```

**Comment by reppair** [comment] 2019-07-09 15:00
I tried it with `addFile()`, `addFileFromPath()`, `addFileFromStream()` and I end with `.zip.cpgz` every time.. Laravel 5.8, php 7.3, ZipStream 0.5.2 .. go figure

**Comment by hazem-taha** [comment] 2021-06-24 14:12
> ```
> ob_end_clean
> ```

Awesome, this worked for me too, thanks
but why did I need to add this ?
